### ISSUE TITLE
Nova funcionalidade - calculadora

### ISSUE THREAD

**Issue by mfmatos** [marcelofmatos/estudos-js#1]
Preciso urgentemente de um botão que calcule a raiz quadrada

**Comment by fernandasantossilva** [comment]
Teste

**Comment by mfmatos** [comment]
![Captura de tela de 2021-09-29 22-10-51](https://user-images.githubusercontent.com/46325500/135369359-38d9bdc7-ba30-4e03-8ab4-44faf2c5cef0.png)

ó, é mais ou menos assim

**Comment by fernandasantossilva** [comment]
Olá,  Marcelo!
Para realizar a inclusão do Botão que calcule a raiz quadrada, necessário que me responda os seguintes questionamentos:

1 - Quem usará essa calculadora? Exemplo: criança? adulto? adolescente?  
2 - Necessário tem mensagem de comando, exemplo: "Digite o Número" ao lado do Campo A e B?
3 - Necessário que tenha o botão  "CE"  limpar registro? 
4 - Na saída do resultado: necessário alguma mensagem?

**Comment by mfmatos** [comment]
Oi Fernanda, seguem as respostas:

1 - Alunos entre 16 e 96 anos que estão aprendendo programação.
2 - Não precisa ter mensagem
3 - O q é CE?
4 - A saída será apenas o resultado no campo Resultado.

**Comment by mfmatos** [comment]
@fernandasantossilva vcs conseguem me entregar quando? Tem uma previsão?

**Comment by fernandasantossilva** [comment]
@mfmatos previsão de entrega para quarta feira - dia 06/10/21.

**Comment by fernandasantossilva** [comment]
Para equipe de Desenvolvedores 
Função nova: Botão para calcular a raiz quadrada

Descrição: ao clicar no botão √, este deve ser capaz de calcular a raiz quadrada de um número digitado. 

Entrada: leitura do número informado no campo A 

Ação: digita um número e pressiona o botão √ (raiz quadrada), a calculadora deverá gerar o resultado. 

Saída: resultado da raiz quadrada

**Comment by fernandasantossilva** [comment]
Para equipe de Desenvolvedores
Dá para a entrega ser dia - dia 06/10/21-  quarta feira?  
Esse prazo foi informado para usuário. 
![caso de uso - calculadora ](https://user-images.githubusercontent.com/90781096/135731269-a6cd6422-926e-488f-bdbd-fa44561f4dd7.png)
